# Site settings
title: Sawyer Hopkins
description: "International Man of Science"
baseurl: ""
url: "http://www.SawyerHopkins.com"

#Social

email: Sawyer@SawyerHopkins.com
twitter_username: Sawyer_Hopkins
github_username:  SawyerHopkins


# Build settings
markdown: kramdown
