# Site settings
title: Sawyer Hopkins
description: "International Man of Science"
baseurl: ""
url: "http://www.SawyerHopkins.com"

#Social

email: Sawyer@SawyerHopkins.com
twitter_username: Sawyer_Hopkins
github_username:  SawyerHopkins

#pagination
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->

#Blogging
author:
  name: Sawyer Hopkins

# Build settings
markdown: kramdown
highlighter: pygments